### ISSUE TITLE
Slider snaps to 100 when initially model-max is not defined

### ISSUE THREAD

**Issue by mathurs** [danielcrisp/angular-rangeslider#37]
I am noticing that the slider jumps to hundred when the value of model-max is not defined. This happens when I am using a field of a json object to bind to model-max. Something like options = {} and model-max binds to options.something. I am also setting pin-handle to min. Even if was set to 0 when null, it would be still graceful.

Thanks

**Comment by danielcrisp** [comment]
Closing unless there are still problems that someone can provide a fiddle for
