### ISSUE TITLE
fractionSize filter option for currency

### ISSUE THREAD

**Issue by ycanales** [danielcrisp/angular-rangeslider#47]
Is there a way to set the `fractionSize` setting for the `currency` filter?
Using the common syntax in either `filter` or `filter-options` attributes won't work (`filter='currency:$:0'`or `filter-options='$:0'`)

**Comment by danielcrisp** [comment]
Not currently, `fractionSize` wasn't an option in the Angular version the directive was originally written for.

Here is the code that filters the value:

https://github.com/danielcrisp/angular-rangeslider/blob/master/angular.rangeSlider.js#L389-L390

Perhaps you can add another attribute that is used for the third argument...? Submit it as a PR and I'll merge it

**Comment by ycanales** [comment]
Great, I submitted a PR.

**Comment by danielcrisp** [comment]
Merged with #48 and #57
