### ISSUE TITLE
Bower.json should list main files

### ISSUE THREAD

**Issue by jordanchapian** [danielcrisp/angular-rangeslider#68]
You should change main files to an array that lists the css dependency as well.

**Comment by NameFILIP** [comment]
This does have the css file: https://github.com/danielcrisp/angular-rangeslider/blob/master/bower.json#L6
Or do you mean something else? Can you provide an example?

**Comment by danielcrisp** [comment]
Perhaps I fixed this but forgot to close the issue. Closing now
