### ISSUE TITLE
Slider works but not seeing min & max values at either end

### ISSUE THREAD

**Issue by jkelleher** [danielcrisp/angular-rangeslider#70]
Maybe I'm missing something but Slider works but not seeing min & max values at either end. Have styling on the slider showing fine and can manipulate the slider but just missing the min/max values at either end under the slider.
Have added my own divs with binding to values which works but I'm pretty sure I should be seeing it by default...

**Comment by danielcrisp** [comment]
Can you see the elements in dev tools?

**Comment by jkelleher** [comment]
![screen shot 2015-05-06 at 18 52 36] 
(https://cloud.githubusercontent.com/assets/2531466/7499681/30ce7ed6-f421-11e4-8970-a8de1cf7dcb8.png)
Daniel,
  not seeing the labels in my devtools, only the slider.

**Comment by danielcrisp** [comment]
Wouldn't they be inside the `range-slider` div... can you expand it?

**Comment by jkelleher** [comment]
Sorry about that - looks like the ngrs divs are actually there but hidden by the 'ng-hide' attribute. So the question moves to why these are hidden by default?
![screen shot 2015-05-07 at 10 28 21](https://cloud.githubusercontent.com/assets/2531466/7512283/da43f450-f4a3-11e4-830c-f5f2c17e089f.png)

**Comment by danielcrisp** [comment]
Well they shouldn't be!

You can see the default setting here and it is `true` so they should be visible: https://github.com/danielcrisp/angular-rangeslider/blob/master/angular.rangeSlider.js#L60

Very strange... I don't suppose you could replicate it in a plunkr/fiddle could you please?

**Comment by jkelleher** [comment]
Daniel, did that up in [Plnkr](http://embed.plnkr.co/yhRIIe/preview) and I see the labels. Trying to think what might be the problem at my end.
I don't think the CSS at my end is the fault as it wouldn't be introducing the ng-hide - but where is that coming from, dunno.

**Comment by danielcrisp** [comment]
Sounds very strange

I added jQuery and the `show-values` attribute and its working fine for me...

http://plnkr.co/edit/wfLEOhsvOrPfexrFypAd?p=preview

Have you tried setting the `show-values` attribute to `true`?

Also you could inspect the directive scope in Chrome using your console or Batarang to see what the value of `showValues` is at runtime

**Comment by jkelleher** [comment]
`show-values="true"` did the trick. Thanks for chasing it down. Strange how I didn't need it in the plnkr but  did in my own app. Still, happy monkey now.

**Comment by danielcrisp** [comment]
Ok glad it worked, I think it might be a hint that something isn't quite right somewhere though

**Comment by Aznbai** [comment]
hello!
same issue as discribed  by @jkelleher.
adding `show-values="true"` to the `  <div range-slider >` did the job.

it actualy worked when i downloaded your ZIP and played with it.
the issue started as i installed angular-rangeslider into my project with bower.

**Comment by Black-Star** [comment]
Is there a way to format number in show values?
it is displaying -> 10000
would like to display  -> 10,000
