### ISSUE TITLE
Set up a background for the slider area

### ISSUE THREAD

**Issue by nuno-mrks** [danielcrisp/angular-rangeslider#79]
Would it be possible to an element to the slider template in order to show a background of the available area of the slider?

![Slider customization](https://dl.dropboxusercontent.com/u/5376441/slider.jpg)

The changes I made were to include the following element before 'ngrs-join'.
`<div class="ngrs-join-bg"></div>`

and styled it as follows:
`    .ngrs-range-slider .ngrs-join-bg {
      position: absolute;
      z-index: 0;
      top: 50%;
      width: 100%;
      left: 0;
      right: 100%;
      height: 3px;
      margin: -1.5px 0 0 0;
      border-radius: 0;
      background-color: #cdccd2;
    }`

This way, if there are no visibile borders on the slider container, the background could act as a guide for it, and adds another customization feeling to the directive.
If this is already possible, please let me know, as I wasn't able to do it without my own modifications.

Thanks

**Comment by danielcrisp** [comment]
If you are removing the borders from `.ngrs-range-slider` can't you just change the `background` at the same time?

Or maybe, judging from your example code, you could just apply your background colour to the `.ngrs-runner` element...?

**Comment by danielcrisp** [comment]
Like this... http://plnkr.co/edit/drP59k2ZCBjPrVvEZiBs?p=preview

**Comment by nuno-mrks** [comment]
Yes, that solved it.
Thank you for your help, and sorry for opening an issue when there wasn't a need for one.

**Comment by danielcrisp** [comment]
No problem, glad I could help
