### ISSUE TITLE
Changing orientation on the fly results into broken output

### ISSUE THREAD

**Issue by stefanwalther** [danielcrisp/angular-rangeslider#90]
Hi,

changing the orientation on the fly results into the following broken output.

![angular-range-slider-broken](https://cloud.githubusercontent.com/assets/669728/10924587/ea006cbc-8287-11e5-9352-26685280a8a3.png)

Tried to fix it by calling `setMinMax` at the end of `attrs.$observe( 'orientation', function ( val ) {` which results into a better state, but still with some weird stylings:

![setminmax](https://cloud.githubusercontent.com/assets/669728/10924736/1d4890da-8289-11e5-8caf-1f56dea9b8d4.png)

Any idea how to solve that and what could be the reason?

Thx a lot in advance & regards
Stefan

**Comment by danielcrisp** [comment]
Does your PR #89 fix this issue?

I'd imagine the problems are caused by the CSS `top` and `left` values not being cleaned properly. To be honest this is never a situation I envisaged so it doesn't actually support changing the orientation on the fly

**Comment by stefanwalther** [comment]
No, #89 does not fix the issue.

**Comment by stefanwalther** [comment]
@danielcrisp I have updated #89 and solved this issue, orientation can now be changed on the fly and is fully working. Some changes were necessary though.
