### ISSUE TITLE
angular2 support

### ISSUE THREAD

**Issue by jabolopes** [danielcrisp/angular-rangeslider#94]
Hi,

I would like to use the angular-rangeslider from Angular2.
Is that possible? If so, what steps are necessary to install it?

Thanks,
Jose

**Comment by danielcrisp** [comment]
No idea, sorry :-)

I've not had a chance to play with Angular 2 yet - give it a go

I'd be surprised if it worked as it was build to work with v1.0.8

**Comment by jabolopes** [comment]
Thanks for the reply.
I decided to go with JQuery UI, since they also have a range slider.
It required a bit of hacking but in the end it worked pretty well.
Also, Angular2 is pretty cool, so do check it out :)
