### ISSUE TITLE
show-values not working .

### ISSUE THREAD

**Issue by umair-khanzada** [danielcrisp/angular-rangeslider#97]
show values attribute is not working i implement like this : `show-values="false"`
below is my code .

`<div class="price-range" range-slider min="0" max="1000000000000" model-max="purchasePrice" pin-handle="min" show-values="false" on-handle-up="output()" show-values="false"></div>
`

**Comment by danielcrisp** [comment]
There is no `show-values` option... what are you expecting to happen?

**Comment by umair-khanzada** [comment]
check this: http://danielcrisp.github.io/angular-rangeslider/demo/

**Comment by danielcrisp** [comment]
Ahh you're right - a secret option!

It might be because you've defined it twice - maybe - not sure

> `<div class="price-range" range-slider min="0" max="1000000000000" model-max="purchasePrice" pin-handle="min" show-values="false" on-handle-up="output()" show-values="false"></div>`

**Comment by umair-khanzada** [comment]
removed one extra but not work .

**Comment by danielcrisp** [comment]
Can you post your code somewhere? JSFiddle? Plnkr?

**Comment by umair-khanzada** [comment]
okie

**Comment by umair-khanzada** [comment]
sorry everyone :100: specialy @danielcrisp 
conflict with my internal css
